---
apiVersion: v1
kind: Namespace
metadata:
  name: game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game
  name: deployment-game
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-game
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-game
    spec:
      containers:
      - image: public.ecr.aws/kishorj/docker-2048:latest
        imagePullPolicy: Always
        name: app-game
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: game
  name: service-game
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-game
