apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- ../../manifest/development/game
- ../../manifest/production/game

namespace: game
commonLabels:
  app.kubernetes.io/managed-by: argocd