# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: guestbook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: guestbook
  name: deployment-guestbook-ui-production
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app-guestbook-ui-production
  template:
    metadata:
      labels:
        app: app-guestbook-ui-production
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: app-guestbook-ui-production
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: guestbook
  name: service-guestbook-ui-production
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app-guestbook-ui-production